[project]
name = "tcc"
version = "0.0.1"
description = "Trabalho de conclusão de curso de ciência da computação"

authors = [
    { name = "thiagopls1", email = "thiagopls1@hotmail.com" },
    { name = "Resutemon1", email = "resutemon@gmail.com" },
    { name = "viniciusegydio", email = "egydiovinicius022@gmail.com" },
]

license = "MIT"
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = ["simpy (>=4.1.2,<5.0.0)"]

[dependency-groups]
dev = [
    "taskipy (>=1.14.1,<2.0.0)",
    "black (>=26.5.1,<27.0.0)",
    "pytest (>=9.1.1,<10.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[tool.taskipy.tasks]
"run" = "python src/main.py"
"build:article" = "cd ./tcc2 && latexmk -f -pdf tcc.tex"
"lint:black:check" = "black --check ."
"lint:black:fix" = "black ."
